
import type { Job, Technician, Contract, Equipment, CustomerData, ProfileChangeRequest, JobStatus, ChatMessage, TechnicianSkill, UserProfile } from '@/types';
import { addDays, subDays, subMinutes, subMonths, setHours, setMinutes } from 'date-fns';
import type { User } from 'firebase/auth';

export const MOCK_COMPANY_ID = 'mock_company_123';
export const MOCK_ADMIN_ID = 'mock_admin_id';

// --- Base User & Company ---
export const MOCK_ADMIN_USER: User = { uid: MOCK_ADMIN_ID, email: 'admin@mock.com' } as User;
export const MOCK_ADMIN_PROFILE: UserProfile = {
  uid: MOCK_ADMIN_ID,
  email: 'admin@mock.com',
  companyId: MOCK_COMPANY_ID,
  role: 'superAdmin',
  onboardingStatus: 'completed',
};
export const MOCK_COMPANY: Company = {
  id: MOCK_COMPANY_ID,
  name: 'Mock Service Company',
  ownerId: MOCK_ADMIN_ID,
  subscriptionStatus: 'active',
  technicianSeatCount: 10,
  settings: {
    companySpecialties: ["HVAC", "Plumbing"],
    hideHelpButton: false
  }
};


export const mockTechnicians: Technician[] = [
  {
    id: 'tech_1',
    companyId: MOCK_COMPANY_ID,
    name: 'Alice Johnson',
    email: 'alice.j@example.com',
    phone: '555-0101',
    isAvailable: false,
    skills: [{name: 'HVAC'}, {name: 'AC Repair'}, {name: 'Furnace Maintenance'}, {name: 'Refrigerant Handling'}],
    location: { latitude: 34.0522, longitude: -118.2437, address: 'Los Angeles, CA' },
    avatarUrl: 'https://placehold.co/100x100.png',
    isOnCall: true,
    currentJobId: 'job_1',
  },
  {
    id: 'tech_2',
    companyId: MOCK_COMPANY_ID,
    name: 'Bob Williams',
    email: 'bob.w@example.com',
    phone: '555-0102',
    isAvailable: true,
    skills: [{name: 'Plumbing'}, {name: 'Pipe Fitting'}, {name: 'Leak Detection'}, {name: 'Water Heater Repair'}, {name: 'HVAC'}, {name: 'AC Repair'}],
    location: { latitude: 34.0582, longitude: -118.2517, address: 'Glendale, CA' },
    avatarUrl: 'https://placehold.co/100x100.png',
    currentJobId: null,
  },
  {
    id: 'tech_3',
    companyId: MOCK_COMPANY_ID,
    name: 'Charlie Brown',
    email: 'charlie.b@example.com',
    phone: '555-0103',
    isAvailable: true,
    skills: [{name: 'Electrical'}, {name: 'Wiring and Rewiring'}, {name: 'Circuit Breaker Repair'}],
    location: { latitude: 34.1522, longitude: -118.2637, address: 'Burbank, CA' },
    avatarUrl: 'https://placehold.co/100x100.png',
    currentJobId: null,
  },
];

// --- Technician User Profiles for Impersonation ---
export const mockTechnicianProfiles: UserProfile[] = mockTechnicians.map(tech => ({
    uid: tech.id,
    email: tech.email,
    companyId: MOCK_COMPANY_ID,
    role: 'technician',
    onboardingStatus: 'completed',
}));


const today = new Date();
const tomorrow = addDays(today, 1);
const dayAfter = addDays(today, 2);

export const mockJobs: Job[] = [
  // Existing jobs, updated with dynamic dates
  {
    id: 'job_1',
    companyId: MOCK_COMPANY_ID,
    title: 'Urgent: No Hot Water',
    description: 'Customer reports no hot water. Suspect faulty water heater element.',
    priority: 'High',
    status: 'Assigned',
    assignedTechnicianId: 'tech_1',
    location: { latitude: 34.0622, longitude: -118.2537, address: '123 Maple St, Los Angeles, CA' },
    customerName: 'Eve Davis',
    customerPhone: '555-0201',
    requiredSkills: ['Water Heater Repair', 'Plumbing'],
    createdAt: subDays(today, 2).toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: setMinutes(setHours(today, 9), 30).toISOString(),
    routeOrder: 0,
  },
  {
    id: 'job_2',
    companyId: MOCK_COMPANY_ID,
    title: 'AC Unit Not Cooling',
    description: 'The main AC unit is running but not blowing cold air. It might be a refrigerant leak or a capacitor issue.',
    priority: 'Medium',
    status: 'Pending',
    assignedTechnicianId: null,
    location: { latitude: 34.0422, longitude: -118.2337, address: '456 Oak Ave, Los Angeles, CA' },
    customerName: 'Frank Miller',
    customerPhone: '555-0202',
    requiredSkills: ['HVAC', 'AC Repair'],
    createdAt: subDays(today, 1).toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: setMinutes(setHours(tomorrow, 10), 0).toISOString(),
    estimatedDurationMinutes: 120,
  },
  {
    id: 'job_16_frank',
    companyId: MOCK_COMPANY_ID,
    title: 'Initial AC Diagnostic',
    description: 'Performed initial check on AC unit. It is running but not cooling. Customer approved a follow-up repair visit.',
    priority: 'Medium',
    status: 'Completed',
    assignedTechnicianId: 'tech_1',
    location: { latitude: 34.0422, longitude: -118.2337, address: '456 Oak Ave, Los Angeles, CA' },
    customerName: 'Frank Miller',
    customerPhone: '555-0202',
    requiredSkills: ['HVAC', 'AC Repair'],
    createdAt: subDays(today, 7).toISOString(),
    updatedAt: subDays(today, 7).toISOString(),
    scheduledTime: subDays(today, 7).toISOString(),
    completedAt: subDays(today, 7).toISOString(),
    notes: 'Confirmed refrigerant levels are low and capacitor is weak. Will need to bring replacement parts on next visit.',
    photos: [
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png'
    ]
  },
  {
    id: 'job_3',
    companyId: MOCK_COMPANY_ID,
    title: 'Outlet Sparking',
    description: 'Kitchen outlet is sparking when a plug is inserted. Potentially dangerous.',
    priority: 'High',
    status: 'Assigned',
    assignedTechnicianId: 'tech_1',
    location: { latitude: 34.0722, longitude: -118.2637, address: '789 Pine Ln, Los Angeles, CA' },
    customerName: 'Grace Wilson',
    customerPhone: '555-0203',
    requiredSkills: ['Electrical', 'Outlet Installation'],
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: setMinutes(setHours(today, 11), 0).toISOString(),
    estimatedDurationMinutes: 60,
    routeOrder: 1,
  },
  {
    id: 'job_4',
    companyId: MOCK_COMPANY_ID,
    title: 'Quarterly HVAC Inspection',
    description: 'Routine maintenance and filter change for the commercial HVAC system.',
    priority: 'Low',
    status: 'Assigned',
    assignedTechnicianId: 'tech_1',
    location: { latitude: 34.0322, longitude: -118.2237, address: '101 Business Blvd, Los Angeles, CA' },
    customerName: 'Heidi Inc.',
    customerPhone: '555-0204',
    createdAt: subDays(today, 10).toISOString(),
    updatedAt: subDays(today, 8).toISOString(),
    scheduledTime: setMinutes(setHours(today, 14), 0).toISOString(),
    routeOrder: 2,
  },
  {
    id: 'job_5',
    companyId: MOCK_COMPANY_ID,
    title: 'Furnace Checkup',
    description: 'Annual furnace maintenance and safety check before winter.',
    priority: 'Medium',
    status: 'Assigned',
    assignedTechnicianId: 'tech_1',
    location: { latitude: 34.0822, longitude: -118.2837, address: '222 Birch Rd, Los Angeles, CA' },
    customerName: 'Ivan Petrov',
    customerPhone: '555-0205',
    requiredSkills: ['HVAC', 'Furnace Maintenance'],
    createdAt: subDays(today, 3).toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: setMinutes(setHours(today, 16), 0).toISOString(),
    routeOrder: 3,
  },
  // New Mock Jobs
  {
    id: 'job_6',
    companyId: MOCK_COMPANY_ID,
    title: 'Leaky Faucet in Bathroom',
    description: 'Constant drip from the bathroom sink faucet. Needs new washer or cartridge.',
    priority: 'Low',
    status: 'Pending',
    assignedTechnicianId: null,
    location: { latitude: 34.055, longitude: -118.25, address: '321 Elm St, Los Angeles, CA' },
    customerName: 'Judy Garland',
    customerPhone: '555-0206',
    requiredSkills: ['Plumbing', 'Faucet Repair'],
    createdAt: subDays(today, 1).toISOString(),
    updatedAt: subDays(today, 1).toISOString(),
    scheduledTime: setMinutes(setHours(tomorrow, 11), 0).toISOString(),
    estimatedDurationMinutes: 45,
  },
  {
    id: 'job_7',
    companyId: MOCK_COMPANY_ID,
    title: 'Install New Ceiling Fan',
    description: 'Customer bought a new ceiling fan and needs it installed in the master bedroom.',
    priority: 'Medium',
    status: 'Pending',
    assignedTechnicianId: null,
    location: { latitude: 34.1, longitude: -118.3, address: '555 Hollywood Blvd, Los Angeles, CA' },
    customerName: 'Kirk Douglas',
    customerPhone: '555-0207',
    requiredSkills: ['Electrical', 'Lighting Installation'],
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: setMinutes(setHours(dayAfter, 9), 0).toISOString(),
    estimatedDurationMinutes: 90,
  },
  {
    id: 'job_8',
    companyId: MOCK_COMPANY_ID,
    title: 'Refrigerator Not Cooling',
    description: 'The freezer is working, but the refrigerator section is warm. Coils might be dirty.',
    priority: 'Medium',
    status: 'Assigned',
    assignedTechnicianId: 'tech_2',
    location: { latitude: 34.02, longitude: -118.4, address: '876 Santa Monica Pier, Santa Monica, CA' },
    customerName: 'Lana Turner',
    customerPhone: '555-0208',
    requiredSkills: ['Appliance Repair', 'Refrigerator Repair'],
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: setMinutes(setHours(today, 13), 0).toISOString(),
    estimatedDurationMinutes: 75,
  },
  {
    id: 'job_9',
    companyId: MOCK_COMPANY_ID,
    title: 'Clogged Main Drain',
    description: 'Multiple drains in the house are backing up. Suspects main line clog.',
    priority: 'High',
    status: 'Assigned',
    assignedTechnicianId: 'tech_2',
    location: { latitude: 33.95, longitude: -118.35, address: '901 Crenshaw Blvd, Inglewood, CA' },
    customerName: 'Marlon Brando',
    customerPhone: '555-0209',
    requiredSkills: ['Plumbing', 'Drain Cleaning'],
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: setMinutes(setHours(today, 10), 0).toISOString(),
    estimatedDurationMinutes: 120,
  },
  {
    id: 'job_10',
    companyId: MOCK_COMPANY_ID,
    title: 'GFCI Outlet Resetting',
    description: 'Garage GFCI outlet keeps tripping. Needs to be inspected and possibly replaced.',
    priority: 'Low',
    status: 'Assigned',
    assignedTechnicianId: 'tech_3',
    location: { latitude: 34.2, longitude: -118.5, address: '1234 Valley Circle, San Fernando, CA' },
    customerName: 'Nina Simone',
    customerPhone: '555-0210',
    requiredSkills: ['Electrical', 'Outlet Installation'],
    createdAt: subDays(today, 2).toISOString(),
    updatedAt: subDays(today, 1).toISOString(),
    scheduledTime: setMinutes(setHours(tomorrow, 14), 0).toISOString(),
    estimatedDurationMinutes: 60,
  },
   {
    id: 'job_11',
    companyId: MOCK_COMPANY_ID,
    title: 'Water Heater Pilot Light Out',
    description: 'Pilot light on gas water heater will not stay lit.',
    priority: 'Medium',
    status: 'Assigned',
    assignedTechnicianId: 'tech_2',
    location: { latitude: 34.05, longitude: -118.45, address: '567 Wilshire Blvd, Beverly Hills, CA' },
    customerName: 'Oscar Peterson',
    customerPhone: '555-0211',
    requiredSkills: ['Water Heater Repair'],
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: setMinutes(setHours(today, 15), 0).toISOString(),
    estimatedDurationMinutes: 90,
  },
   {
    id: 'job_12',
    companyId: MOCK_COMPANY_ID,
    title: 'Dryer Not Heating',
    description: 'The dryer tumbles but does not produce any heat. Heating element might be broken.',
    priority: 'Low',
    status: 'Completed',
    assignedTechnicianId: 'tech_3',
    location: { latitude: 34.08, longitude: -118.35, address: '789 Melrose Ave, West Hollywood, CA' },
    customerName: 'Quincy Jones',
    customerPhone: '555-0212',
    requiredSkills: ['Appliance Repair'],
    createdAt: subDays(today, 3).toISOString(),
    updatedAt: subDays(today, 3).toISOString(),
    scheduledTime: subDays(today, 3).toISOString(),
    completedAt: subDays(today, 3).toISOString(),
    estimatedDurationMinutes: 60,
  },
   {
    id: 'job_13',
    companyId: MOCK_COMPANY_ID,
    title: 'Install Outdoor Lighting',
    description: 'Customer wants new landscape lighting installed in their front yard.',
    priority: 'Medium',
    status: 'Completed',
    assignedTechnicianId: 'tech_3',
    location: { latitude: 34.15, longitude: -118.4, address: '101 Ventura Blvd, Studio City, CA' },
    customerName: 'Ray Charles',
    customerPhone: '555-0213',
    requiredSkills: ['Electrical', 'Lighting Installation'],
    createdAt: subDays(today, 4).toISOString(),
    updatedAt: subDays(today, 4).toISOString(),
    scheduledTime: subDays(today, 4).toISOString(),
    completedAt: subDays(today, 4).toISOString(),
    estimatedDurationMinutes: 180,
  },
   {
    id: 'job_14',
    companyId: MOCK_COMPANY_ID,
    title: 'Dishwasher Leaking',
    description: 'Small puddle of water appears under the dishwasher after running a cycle.',
    priority: 'High',
    status: 'Assigned',
    assignedTechnicianId: 'tech_2',
    location: { latitude: 34.06, longitude: -118.3, address: '456 La Brea Ave, Los Angeles, CA' },
    customerName: 'Stevie Wonder',
    customerPhone: '555-0214',
    requiredSkills: ['Plumbing', 'Leak Detection', 'Appliance Repair'],
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: setMinutes(setHours(today, 14), 30).toISOString(),
    estimatedDurationMinutes: 75,
  },
   {
    id: 'job_15',
    companyId: MOCK_COMPANY_ID,
    title: 'Draft Job Example',
    description: 'This is a job created by a CSR that needs dispatcher review.',
    priority: 'Medium',
    status: 'Draft',
    assignedTechnicianId: 'tech_3',
    location: { latitude: 34.0, longitude: -118.2, address: '777 Draft Dr, Los Angeles, CA' },
    customerName: 'Tina Turner',
    customerPhone: '555-0215',
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: null,
    estimatedDurationMinutes: 60,
  },
];

export const mockContracts: Contract[] = [
    {
        id: 'contract_1',
        companyId: MOCK_COMPANY_ID,
        customerName: 'Downtown Office Complex',
        customerAddress: '200 Financial Dr, Los Angeles, CA',
        frequency: 'Quarterly',
        startDate: subDays(new Date(), 90).toISOString(),
        isActive: true,
        jobTemplate: {
            title: 'Quarterly HVAC Maintenance',
            description: 'Perform standard quarterly HVAC system check, clean filters, and inspect for wear and tear.',
            priority: 'Low',
            estimatedDurationMinutes: 180,
        },
        lastGeneratedUntil: subDays(new Date(), 1).toISOString(),
        createdAt: subDays(new Date(), 90).toISOString(),
    },
    {
        id: 'contract_2',
        companyId: MOCK_COMPANY_ID,
        customerName: 'Sunset Apartments',
        customerAddress: '800 Sunset Blvd, Los Angeles, CA',
        frequency: 'Monthly',
        startDate: '2023-01-15T09:00:00.000Z',
        isActive: true,
        jobTemplate: {
            title: 'Monthly Fire Extinguisher Check',
            description: 'Inspect and certify all fire extinguishers in common areas.',
            priority: 'Medium',
            estimatedDurationMinutes: 90,
        },
        // This date is now set to 1 month ago, so the next due date is today.
        lastGeneratedUntil: subMonths(new Date(), 1).toISOString(), 
        createdAt: '2023-01-15T09:00:00.000Z',
    },
];

export const mockCustomers: CustomerData[] = [
    { id: 'cust_1', companyId: MOCK_COMPANY_ID, name: 'Eve Davis', phone: '555-0201', email: 'eve.d@example.com', address: '123 Maple St, Los Angeles, CA', createdAt: subDays(new Date(), 2).toISOString() },
    { id: 'cust_2', companyId: MOCK_COMPANY_ID, name: 'Frank Miller', phone: '555-0202', email: 'frank.m@example.com', address: '456 Oak Ave, Los Angeles, CA', createdAt: subDays(new Date(), 1).toISOString() },
];

export const mockEquipment: Equipment[] = [
    { id: 'equip_1', companyId: MOCK_COMPANY_ID, customerId: 'cust_1', customerName: 'Eve Davis', name: 'Rheem Water Heater', model: 'XE50M06ST45U1', installDate: '2022-05-10', createdAt: '2022-05-10' },
];

export const mockProfileChangeRequests: ProfileChangeRequest[] = [
    {
        id: 'pcr_1',
        companyId: MOCK_COMPANY_ID,
        technicianId: 'tech_1',
        technicianName: 'Alice Johnson',
        requestedChanges: {
            phone: '555-0105',
            skills: ['HVAC', 'AC Repair', 'Furnace Maintenance', 'Refrigerant Handling', 'Boiler Repair'],
        },
        notes: 'Updated my phone number and added a new skill certification for boilers.',
        status: 'pending',
        createdAt: new Date().toISOString(),
    }
];

export const mockChatMessages: ChatMessage[] = [
    {
        id: 'msg_1',
        jobId: 'job_1',
        companyId: MOCK_COMPANY_ID,
        senderId: 'tech_1',
        senderName: 'Alice Johnson',
        receiverId: MOCK_ADMIN_ID,
        text: "I'm on my way to the 'No Hot Water' job. The previous one took a bit longer than expected.",
        timestamp: subMinutes(new Date(), 15).toISOString(),
        isRead: true,
    },
    {
        id: 'msg_2',
        jobId: 'job_1',
        companyId: MOCK_COMPANY_ID,
        senderId: MOCK_ADMIN_ID,
        senderName: 'Dispatcher',
        receiverId: 'tech_1',
        text: "Thanks for the update, Alice. Keep me posted if there are any issues finding the site.",
        timestamp: subMinutes(new Date(), 14).toISOString(),
        isRead: true,
    },
     {
        id: 'msg_3',
        jobId: 'job_3',
        companyId: MOCK_COMPANY_ID,
        senderId: MOCK_ADMIN_ID,
        senderName: 'Dispatcher',
        receiverId: 'tech_1',
        text: "After the 'Outlet Sparking' job, please check if you have a spare 20A breaker in your van. The next customer might need one.",
        timestamp: subMinutes(new Date(), 5).toISOString(),
        isRead: false,
    },
];
