
import type { Job, Technician, Contract, Equipment, CustomerData, ProfileChangeRequest, JobStatus, ChatMessage, TechnicianSkill, UserProfile } from '@/types';
import { addDays, subDays, subMinutes, subMonths, setHours, setMinutes } from 'date-fns';
import type { User } from 'firebase/auth';

export const MOCK_COMPANY_ID = 'mock_company_123';
export const MOCK_ADMIN_ID = 'mock_admin_id';

// --- Base User & Company ---
export const MOCK_ADMIN_USER: User = { uid: MOCK_ADMIN_ID, email: 'admin@mock.com' } as User;
export const MOCK_ADMIN_PROFILE: UserProfile = {
  uid: MOCK_ADMIN_ID,
  email: 'admin@mock.com',
  companyId: MOCK_COMPANY_ID,
  role: 'superAdmin',
  onboardingStatus: 'completed',
};
export const MOCK_COMPANY: Company = {
  id: MOCK_COMPANY_ID,
  name: 'Mock Service Company',
  ownerId: MOCK_ADMIN_ID,
  subscriptionStatus: 'active',
  technicianSeatCount: 10,
  settings: {
    companySpecialties: ["HVAC", "Plumbing"],
    hideHelpButton: false
  }
};


export const mockTechnicians: Technician[] = [
  {
    id: 'tech_1',
    companyId: MOCK_COMPANY_ID,
    name: 'Alice Johnson',
    email: 'alice.j@example.com',
    phone: '555-0101',
    isAvailable: true,
    skills: ['HVAC', 'AC Repair', 'Furnace Maintenance', 'Refrigerant Handling', 'Appliance Repair', 'Refrigerator Repair'],
    location: { latitude: 34.0522, longitude: -118.2437, address: 'Los Angeles, CA' },
    avatarUrl: 'https://placehold.co/100x100/A8D8EA/4A4A4A?text=AJ',
    isOnCall: true,
    currentJobId: 'job_1',
    vanInventory: ["Capacitor", "Filter Drier", "Refrigerant R-410A", "Thermostat"],
    hourlyCost: 75,
    maxDailyHours: 8,
  },
  {
    id: 'tech_2',
    companyId: MOCK_COMPANY_ID,
    name: 'Bob Williams',
    email: 'bob.w@example.com',
    phone: '555-0102',
    isAvailable: true,
    skills: ['Plumbing', 'Pipe Fitting', 'Leak Detection', 'Water Heater Repair', 'HVAC', 'AC Repair', 'Faucet Repair', 'Drain Cleaning', 'Electrical', 'Lighting Installation'],
    location: { latitude: 34.0582, longitude: -118.2517, address: 'Glendale, CA' },
    avatarUrl: 'https://placehold.co/100x100/F4B393/4A4A4A?text=BW',
    currentJobId: null,
    vanInventory: ["P-Trap Assembly", "Faucet Cartridge", "Wax Ring", "Copper Pipe (1/2 in)"],
    hourlyCost: 65,
    maxDailyHours: 10,
  },
  {
    id: 'tech_3',
    companyId: MOCK_COMPANY_ID,
    name: 'Charlie Brown',
    email: 'charlie.b@example.com',
    phone: '555-0103',
    isAvailable: true,
    skills: ['Electrical', 'Wiring and Rewiring', 'Circuit Breaker Repair', 'Lighting Installation', 'Outlet Installation', 'Plumbing', 'Faucet Repair'],
    location: { latitude: 34.1522, longitude: -118.2637, address: 'Burbank, CA' },
    avatarUrl: 'https://placehold.co/100x100/B2E0B6/4A4A4A?text=CB',
    currentJobId: null,
    vanInventory: ["GFCI Outlet", "Circuit Breaker (15A)", "Circuit Breaker (20A)", "Light Switch", "Electrical Wire (12/2)"],
    hourlyCost: 70,
    maxDailyHours: 8,
  },
];

// --- Technician User Profiles for Impersonation ---
export const mockTechnicianProfiles: UserProfile[] = mockTechnicians.map(tech => ({
    uid: tech.id,
    email: tech.email,
    companyId: MOCK_COMPANY_ID,
    role: 'technician',
    onboardingStatus: 'completed',
}));


const today = new Date();
const tomorrow = addDays(today, 1);
const dayAfter = addDays(today, 2);
const threeDaysFromNow = addDays(today, 3);

export const mockJobs: Job[] = [
  // Existing jobs, updated with dynamic dates
  {
    id: 'job_1',
    companyId: MOCK_COMPANY_ID,
    title: 'Urgent: No Hot Water',
    description: 'Customer reports no hot water. Suspect faulty water heater element.',
    priority: 'High',
    status: 'In Progress',
    assignedTechnicianId: 'tech_1',
    location: { latitude: 34.0622, longitude: -118.2537, address: '123 Maple St, Los Angeles, CA' },
    customerId: 'cust_1',
    customerName: 'Eve Davis',
    customerPhone: '555-0201',
    customerEmail: 'eve.d@example.com',
    requiredSkills: ['Water Heater Repair', 'Plumbing'],
    createdAt: subDays(today, 2).toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: setMinutes(setHours(today, 9), 30).toISOString(),
    inProgressAt: subMinutes(new Date(), 20).toISOString(),
    routeOrder: 0,
    estimatedDurationMinutes: 75,
    quotedValue: 350,
    expectedPartsCost: 50,
    profitScore: 285,
  },
  {
    id: 'job_1_history_1',
    companyId: MOCK_COMPANY_ID,
    title: 'Annual HVAC Tune-up',
    description: 'Performed annual cleaning and inspection of HVAC system.',
    priority: 'Low',
    status: 'Completed',
    assignedTechnicianId: 'tech_1',
    location: { latitude: 34.0622, longitude: -118.2537, address: '123 Maple St, Los Angeles, CA' },
    customerId: 'cust_1',
    customerName: 'Eve Davis',
    customerPhone: '555-0201',
    customerEmail: 'eve.d@example.com',
    requiredSkills: ['HVAC', 'Furnace Maintenance'],
    createdAt: subMonths(today, 12).toISOString(),
    updatedAt: subMonths(today, 12).toISOString(),
    scheduledTime: subMonths(today, 12).toISOString(),
    completedAt: subMonths(today, 12).toISOString(),
    notes: 'System is in good condition. Cleaned coils and replaced filter.',
    isFirstTimeFix: true,
    quotedValue: 150,
    actualProfit: 120,
    profitScore: 115,
  },
  {
    id: 'job_2',
    companyId: MOCK_COMPANY_ID,
    title: 'AC Unit Not Cooling',
    description: 'The main AC unit is running but not blowing cold air. It might be a refrigerant leak or a capacitor issue.',
    priority: 'Medium',
    status: 'Unassigned',
    assignedTechnicianId: null,
    location: { latitude: 34.0422, longitude: -118.2337, address: '456 Oak Ave, Los Angeles, CA' },
    customerId: 'cust_2',
    customerName: 'Frank Miller',
    customerPhone: '555-0202',
    customerEmail: 'frank.m@example.com',
    requiredSkills: ['HVAC', 'AC Repair'],
    createdAt: subDays(today, 1).toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: setMinutes(setHours(tomorrow, 10), 0).toISOString(),
    estimatedDurationMinutes: 120,
    quotedValue: 450,
    expectedPartsCost: 80,
  },
  {
    id: 'job_16_frank',
    companyId: MOCK_COMPANY_ID,
    title: 'Initial AC Diagnostic',
    description: 'Performed initial check on AC unit. It is running but not cooling. Customer approved a follow-up repair visit.',
    priority: 'Medium',
    status: 'Completed',
    assignedTechnicianId: 'tech_1',
    location: { latitude: 34.0422, longitude: -118.2337, address: '456 Oak Ave, Los Angeles, CA' },
    customerId: 'cust_2',
    customerName: 'Frank Miller',
    customerPhone: '555-0202',
    customerEmail: 'frank.m@example.com',
    requiredSkills: ['HVAC', 'AC Repair'],
    createdAt: subDays(today, 7).toISOString(),
    updatedAt: subDays(today, 7).toISOString(),
    scheduledTime: subDays(today, 7).toISOString(),
    enRouteAt: subMinutes(new Date(subDays(today, 7)), 30).toISOString(),
    inProgressAt: subMinutes(new Date(subDays(today, 7)), 15).toISOString(),
    completedAt: subDays(today, 7).toISOString(),
    triageImages: ['https://placehold.co/600x400.png?text=Broken+AC+Unit'],
    aiIdentifiedModel: "Trane XR14 (Model: 4TTR4036L1000A)",
    aiSuggestedParts: ["Start Capacitor (P/N CPT00668)", "Contactor (P/N CNT07936)"],
    aiRepairGuide: "1. Disconnect power.\n2. Visually inspect capacitor for bulging.\n3. Test capacitor with multimeter.\n4. Replace capacitor if faulty.\n5. Check contactor for pitting.",
    notes: 'Confirmed refrigerant levels are low and capacitor is weak. Replaced capacitor on-site from van stock. Customer was advised a full refrigerant recharge and leak check is needed on the next visit.',
    photos: [
      'https://placehold.co/600x400.png?text=Old+Capacitor',
      'https://placehold.co/600x400.png?text=New+Capacitor'
    ],
    breaks: [{ start: subMinutes(new Date(subDays(today, 7)), 10).toISOString(), end: new Date(subDays(today, 7)).toISOString() }],
    isFirstTimeFix: false,
    reasonForFollowUp: "Initial visit was for diagnosis only. Customer approved follow-up repair, but required refrigerant was not in van stock.",
    customerSatisfactionScore: 4,
    customerSignatureUrl: "https://placehold.co/300x150.png?text=Frank+Miller",
    customerSignatureTimestamp: subDays(today, 7).toISOString(),
    travelDistanceKm: 12.5,
    co2EmissionsKg: 2.4,
    quotedValue: 200,
    actualProfit: 150,
  },
  {
    id: 'job_20_frank_history',
    companyId: MOCK_COMPANY_ID,
    title: 'Water Heater Flush',
    description: 'Annual water heater flush and maintenance check.',
    priority: 'Low',
    status: 'Completed',
    assignedTechnicianId: 'tech_2',
    location: { latitude: 34.0422, longitude: -118.2337, address: '456 Oak Ave, Los Angeles, CA' },
    customerId: 'cust_2',
    customerName: 'Frank Miller',
    customerPhone: '555-0202',
    customerEmail: 'frank.m@example.com',
    requiredSkills: ['Water Heater Repair', 'Plumbing'],
    createdAt: subDays(today, 90).toISOString(),
    updatedAt: subDays(today, 90).toISOString(),
    scheduledTime: subDays(today, 90).toISOString(),
    completedAt: subDays(today, 90).toISOString(),
    notes: 'Water heater flushed. Anode rod is in good condition. No issues found.',
    isFirstTimeFix: true,
    customerSatisfactionScore: 5,
    quotedValue: 125,
    actualProfit: 100,
  },
  {
    id: 'job_3',
    companyId: MOCK_COMPANY_ID,
    title: 'Outlet Sparking',
    description: 'Kitchen outlet is sparking when a plug is inserted. Potentially dangerous.',
    priority: 'High',
    status: 'Assigned',
    assignedTechnicianId: 'tech_1',
    location: { latitude: 34.0722, longitude: -118.2637, address: '789 Pine Ln, Los Angeles, CA' },
    customerId: 'cust_3',
    customerName: 'Grace Wilson',
    customerPhone: '555-0203',
    requiredSkills: ['Electrical', 'Outlet Installation'],
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: setMinutes(setHours(today, 11), 0).toISOString(),
    estimatedDurationMinutes: 60,
    routeOrder: 1,
    quotedValue: 180,
    expectedPartsCost: 15,
  },
  {
    id: 'job_4',
    companyId: MOCK_COMPANY_ID,
    title: 'Quarterly HVAC Inspection',
    description: 'Routine maintenance and filter change for the commercial HVAC system.',
    priority: 'Low',
    status: 'Assigned',
    assignedTechnicianId: 'tech_1',
    location: { latitude: 34.0322, longitude: -118.2237, address: '101 Business Blvd, Los Angeles, CA' },
    customerId: 'cust_4',
    customerName: 'Heidi Inc.',
    customerPhone: '555-0204',
    createdAt: subDays(today, 10).toISOString(),
    updatedAt: subDays(today, 8).toISOString(),
    scheduledTime: setMinutes(setHours(today, 14), 0).toISOString(),
    routeOrder: 2,
    sourceContractId: 'contract_1',
    estimatedDurationMinutes: 180,
    quotedValue: 500,
    expectedPartsCost: 75,
    profitScore: 400,
  },
  {
    id: 'job_5',
    companyId: MOCK_COMPANY_ID,
    title: 'Furnace Checkup',
    description: 'Annual furnace maintenance and safety check before winter.',
    priority: 'Medium',
    status: 'Assigned',
    assignedTechnicianId: 'tech_1',
    location: { latitude: 34.0822, longitude: -118.2837, address: '222 Birch Rd, Los Angeles, CA' },
    customerId: 'cust_5',
    customerName: 'Ivan Petrov',
    customerPhone: '555-0205',
    requiredSkills: ['HVAC', 'Furnace Maintenance'],
    createdAt: subDays(today, 3).toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: setMinutes(setHours(today, 16), 0).toISOString(),
    routeOrder: 3,
    estimatedDurationMinutes: 60,
    quotedValue: 175,
    expectedPartsCost: 20,
  },
   {
    id: 'job_21_alice_tomorrow',
    companyId: MOCK_COMPANY_ID,
    title: 'Install Smart Thermostat',
    description: 'Customer needs a new Nest thermostat installed.',
    priority: 'Medium',
    status: 'Assigned',
    assignedTechnicianId: 'tech_1',
    location: { latitude: 34.0922, longitude: -118.3, address: '333 Palm Grove, Hollywood, CA' },
    customerId: 'cust_18',
    customerName: 'Victor Hugo',
    customerPhone: '555-0218',
    requiredSkills: ['HVAC', 'Thermostat Installation'],
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: setMinutes(setHours(tomorrow, 9), 0).toISOString(),
    estimatedDurationMinutes: 90,
    quotedValue: 250,
    expectedPartsCost: 150,
  },
  {
    id: 'job_22_alice_tomorrow_pm',
    companyId: MOCK_COMPANY_ID,
    title: 'Appliance Diagnostic: Dishwasher',
    description: 'Dishwasher is not draining. Needs diagnostic.',
    priority: 'Medium',
    status: 'Assigned',
    assignedTechnicianId: 'tech_1',
    location: { latitude: 34.11, longitude: -118.32, address: '444 Hillside Dr, Hollywood Hills, CA' },
    customerId: 'cust_19',
    customerName: 'Walt Disney',
    customerPhone: '555-0219',
    requiredSkills: ['Appliance Repair', 'Leak Detection'],
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: setMinutes(setHours(tomorrow, 13), 30).toISOString(),
    estimatedDurationMinutes: 60,
    quotedValue: 120,
    expectedPartsCost: 10,
  },
  {
    id: 'job_23_alice_dayafter',
    companyId: MOCK_COMPANY_ID,
    title: 'Refrigerator Repair',
    description: 'The refrigerator is making a loud buzzing noise.',
    priority: 'High',
    status: 'Assigned',
    assignedTechnicianId: 'tech_1',
    location: { latitude: 34.06, longitude: -118.35, address: '555 Miracle Mile, Los Angeles, CA' },
    customerId: 'cust_20',
    customerName: 'Xena Warrior',
    customerPhone: '555-0220',
    requiredSkills: ['Appliance Repair', 'Refrigerator Repair'],
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: setMinutes(setHours(dayAfter, 10), 0).toISOString(),
    estimatedDurationMinutes: 75,
    quotedValue: 300,
    expectedPartsCost: 45,
  },
  {
    id: 'job_24_alice_threedays',
    companyId: MOCK_COMPANY_ID,
    title: 'Routine AC Filter Change',
    description: 'Quarterly filter change for office building.',
    priority: 'Low',
    status: 'Assigned',
    assignedTechnicianId: 'tech_1',
    location: { latitude: 34.05, longitude: -118.24, address: '666 Downtown Ave, Los Angeles, CA' },
    customerId: 'cust_4',
    customerName: 'Heidi Inc.',
    customerPhone: '555-0204',
    requiredSkills: ['HVAC'],
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: setMinutes(setHours(threeDaysFromNow, 11), 0).toISOString(),
    estimatedDurationMinutes: 45,
    quotedValue: 95,
    expectedPartsCost: 25,
  },
  {
    id: 'job_6',
    companyId: MOCK_COMPANY_ID,
    title: 'Leaky Faucet in Bathroom',
    description: 'Constant drip from the bathroom sink faucet. Needs new washer or cartridge.',
    priority: 'Low',
    status: 'Unassigned',
    assignedTechnicianId: null,
    location: { latitude: 34.055, longitude: -118.25, address: '321 Elm St, Los Angeles, CA' },
    customerId: 'cust_6',
    customerName: 'Judy Garland',
    customerPhone: '555-0206',
    requiredSkills: ['Plumbing', 'Faucet Repair'],
    createdAt: subDays(today, 1).toISOString(),
    updatedAt: subDays(today, 1).toISOString(),
    scheduledTime: setMinutes(setHours(tomorrow, 11), 0).toISOString(),
    estimatedDurationMinutes: 45,
    quotedValue: 150,
    expectedPartsCost: 5,
  },
  {
    id: 'job_7',
    companyId: MOCK_COMPANY_ID,
    title: 'Install New Ceiling Fan',
    description: 'Customer bought a new ceiling fan and needs it installed in the master bedroom.',
    priority: 'Medium',
    status: 'Unassigned',
    assignedTechnicianId: null,
    location: { latitude: 34.1, longitude: -118.3, address: '555 Hollywood Blvd, Los Angeles, CA' },
    customerId: 'cust_7',
    customerName: 'Kirk Douglas',
    customerPhone: '555-0207',
    requiredSkills: ['Electrical', 'Lighting Installation'],
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: setMinutes(setHours(dayAfter, 9), 0).toISOString(),
    estimatedDurationMinutes: 90,
    quotedValue: 200,
    expectedPartsCost: 0,
  },
  {
    id: 'job_8',
    companyId: MOCK_COMPANY_ID,
    title: 'Refrigerator Not Cooling',
    description: 'The freezer is working, but the refrigerator section is warm. Coils might be dirty.',
    priority: 'Medium',
    status: 'Assigned',
    assignedTechnicianId: 'tech_2',
    location: { latitude: 34.02, longitude: -118.4, address: '876 Santa Monica Pier, Santa Monica, CA' },
    customerId: 'cust_8',
    customerName: 'Lana Turner',
    customerPhone: '555-0208',
    requiredSkills: ['Appliance Repair', 'Refrigerator Repair'],
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: setMinutes(setHours(today, 13), 0).toISOString(),
    estimatedDurationMinutes: 75,
    quotedValue: 220,
    expectedPartsCost: 30,
    profitScore: 175,
  },
  {
    id: 'job_9',
    companyId: MOCK_COMPANY_ID,
    title: 'Clogged Main Drain',
    description: 'Multiple drains in the house are backing up. Suspects main line clog.',
    priority: 'High',
    status: 'Assigned',
    assignedTechnicianId: 'tech_2',
    location: { latitude: 33.95, longitude: -118.35, address: '901 Crenshaw Blvd, Inglewood, CA' },
    customerId: 'cust_9',
    customerName: 'Marlon Brando',
    customerPhone: '555-0209',
    requiredSkills: ['Plumbing', 'Drain Cleaning'],
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: setMinutes(setHours(today, 10), 0).toISOString(),
    estimatedDurationMinutes: 120,
    quotedValue: 550,
    expectedPartsCost: 0,
  },
  {
    id: 'job_10',
    companyId: MOCK_COMPANY_ID,
    title: 'GFCI Outlet Resetting',
    description: 'Garage GFCI outlet keeps tripping. Needs to be inspected and possibly replaced.',
    priority: 'Low',
    status: 'Assigned',
    assignedTechnicianId: 'tech_3',
    location: { latitude: 34.2, longitude: -118.5, address: '1234 Valley Circle, San Fernando, CA' },
    customerId: 'cust_10',
    customerName: 'Nina Simone',
    customerPhone: '555-0210',
    requiredSkills: ['Electrical', 'Outlet Installation'],
    createdAt: subDays(today, 2).toISOString(),
    updatedAt: subDays(today, 1).toISOString(),
    scheduledTime: setMinutes(setHours(tomorrow, 14), 0).toISOString(),
    estimatedDurationMinutes: 60,
    quotedValue: 160,
    expectedPartsCost: 20,
  },
   {
    id: 'job_11',
    companyId: MOCK_COMPANY_ID,
    title: 'Water Heater Pilot Light Out',
    description: 'Pilot light on gas water heater will not stay lit.',
    priority: 'Medium',
    status: 'Assigned',
    assignedTechnicianId: 'tech_2',
    location: { latitude: 34.05, longitude: -118.45, address: '567 Wilshire Blvd, Beverly Hills, CA' },
    customerId: 'cust_11',
    customerName: 'Oscar Peterson',
    customerPhone: '555-0211',
    requiredSkills: ['Water Heater Repair'],
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: setMinutes(setHours(today, 15), 0).toISOString(),
    estimatedDurationMinutes: 90,
    quotedValue: 280,
    expectedPartsCost: 70,
  },
   {
    id: 'job_12',
    companyId: MOCK_COMPANY_ID,
    title: 'Dryer Not Heating',
    description: 'The dryer tumbles but does not produce any heat. Heating element might be broken.',
    priority: 'Low',
    status: 'Completed',
    assignedTechnicianId: 'tech_3',
    location: { latitude: 34.08, longitude: -118.35, address: '789 Melrose Ave, West Hollywood, CA' },
    customerId: 'cust_12',
    customerName: 'Quincy Jones',
    customerPhone: '555-0212',
    requiredSkills: ['Appliance Repair'],
    createdAt: subDays(today, 3).toISOString(),
    updatedAt: subDays(today, 3).toISOString(),
    scheduledTime: subDays(today, 3).toISOString(),
    completedAt: subDays(today, 3).toISOString(),
    estimatedDurationMinutes: 60,
    notes: "Replaced the heating element. Dryer is now heating correctly. Tested on high heat for 10 minutes.",
    isFirstTimeFix: true,
    customerSatisfactionScore: 5,
    quotedValue: 210,
    actualProfit: 140,
    profitScore: 135,
  },
   {
    id: 'job_13',
    companyId: MOCK_COMPANY_ID,
    title: 'Install Outdoor Lighting',
    description: 'Customer wants new landscape lighting installed in their front yard.',
    priority: 'Medium',
    status: 'Completed',
    assignedTechnicianId: 'tech_3',
    location: { latitude: 34.15, longitude: -118.4, address: '101 Ventura Blvd, Studio City, CA' },
    customerId: 'cust_13',
    customerName: 'Ray Charles',
    customerPhone: '555-0213',
    requiredSkills: ['Electrical', 'Lighting Installation'],
    createdAt: subDays(today, 4).toISOString(),
    updatedAt: subDays(today, 4).toISOString(),
    scheduledTime: subDays(today, 4).toISOString(),
    completedAt: subDays(today, 4).toISOString(),
    estimatedDurationMinutes: 180,
    notes: "Installed 6 low-voltage path lights and 2 spotlights. All connected to a new transformer and timer. Customer is happy with the result.",
    isFirstTimeFix: true,
    customerSatisfactionScore: 5,
    quotedValue: 800,
    actualProfit: 450,
  },
   {
    id: 'job_14',
    companyId: MOCK_COMPANY_ID,
    title: 'Dishwasher Leaking',
    description: 'Small puddle of water appears under the dishwasher after running a cycle.',
    priority: 'High',
    status: 'Assigned',
    assignedTechnicianId: 'tech_2',
    location: { latitude: 34.06, longitude: -118.3, address: '456 La Brea Ave, Los Angeles, CA' },
    customerId: 'cust_14',
    customerName: 'Stevie Wonder',
    customerPhone: '555-0214',
    requiredSkills: ['Plumbing', 'Leak Detection', 'Appliance Repair'],
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: setMinutes(setHours(today, 14), 30).toISOString(),
    estimatedDurationMinutes: 75,
    quotedValue: 260,
    expectedPartsCost: 25,
  },
   {
    id: 'job_15',
    companyId: MOCK_COMPANY_ID,
    title: 'Draft Job Example',
    description: 'This is a job created by a CSR that needs dispatcher review.',
    priority: 'Medium',
    status: 'Draft',
    assignedTechnicianId: null,
    location: { latitude: 34.0, longitude: -118.2, address: '777 Draft Dr, Los Angeles, CA' },
    customerId: 'cust_15',
    customerName: 'Tina Turner',
    customerPhone: '555-0215',
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: null,
    estimatedDurationMinutes: 60,
    quotedValue: 100,
    expectedPartsCost: 0,
  },
  {
    id: 'job_17_unassigned',
    companyId: MOCK_COMPANY_ID,
    title: 'Commercial AC Unit #3 Down',
    description: 'One of the three rooftop units at the downtown office is not responsive. Needs urgent repair.',
    priority: 'High',
    status: 'Unassigned',
    assignedTechnicianId: null,
    location: { latitude: 34.05, longitude: -118.24, address: '200 Financial Dr, Los Angeles, CA' },
    customerId: 'cust_4',
    customerName: 'Heidi Inc.',
    customerPhone: '555-0301',
    requiredSkills: ['HVAC', 'AC Repair', 'Refrigerant Handling'],
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: null,
    estimatedDurationMinutes: 240,
    quotedValue: 1200,
    expectedPartsCost: 350,
  },
  {
    id: 'job_18_unassigned',
    companyId: MOCK_COMPANY_ID,
    title: 'Landscape Lighting Flickering',
    description: 'The lights along the main walkway are flickering. May be a wiring issue or a faulty transformer.',
    priority: 'Low',
    status: 'Unassigned',
    assignedTechnicianId: null,
    location: { latitude: 34.1, longitude: -118.34, address: '500 Griffith Park Dr, Los Angeles, CA' },
    customerId: 'cust_16',
    customerName: 'Park Authority',
    customerPhone: '555-0302',
    requiredSkills: ['Electrical', 'Lighting Installation'],
    createdAt: subDays(today, 1).toISOString(),
    updatedAt: subDays(today, 1).toISOString(),
    scheduledTime: null,
    estimatedDurationMinutes: 120,
    quotedValue: 400,
    expectedPartsCost: 100,
  },
  {
    id: 'job_19_unassigned',
    companyId: MOCK_COMPANY_ID,
    title: 'Install New Kitchen Faucet',
    description: 'Customer has purchased a new faucet and needs their old one removed and the new one installed.',
    priority: 'Medium',
    status: 'Unassigned',
    assignedTechnicianId: null,
    location: { latitude: 34.07, longitude: -118.36, address: '800 Grove St, Los Angeles, CA' },
    customerId: 'cust_17',
    customerName: 'Ursula K. Le Guin',
    customerPhone: '555-0216',
    requiredSkills: ['Plumbing', 'Faucet Repair'],
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    scheduledTime: setMinutes(setHours(tomorrow, 13), 0).toISOString(),
    estimatedDurationMinutes: 60,
    quotedValue: 180,
    expectedPartsCost: 0,
  }
];

export const mockContracts: Contract[] = [
    {
        id: 'contract_1',
        companyId: MOCK_COMPANY_ID,
        customerName: 'Heidi Inc.',
        customerAddress: '101 Business Blvd, Los Angeles, CA',
        frequency: 'Quarterly',
        startDate: subDays(new Date(), 90).toISOString(),
        isActive: true,
        jobTemplate: {
            title: 'Quarterly HVAC Maintenance',
            description: 'Perform standard quarterly HVAC system check, clean filters, and inspect for wear and tear.',
            priority: 'Low',
            estimatedDurationMinutes: 180,
        },
        lastGeneratedUntil: subDays(new Date(), 1).toISOString(),
        createdAt: subDays(new Date(), 90).toISOString(),
    },
    {
        id: 'contract_2',
        companyId: MOCK_COMPANY_ID,
        customerName: 'Sunset Apartments',
        customerAddress: '800 Sunset Blvd, Los Angeles, CA',
        frequency: 'Monthly',
        startDate: '2023-01-15T09:00:00.000Z',
        isActive: true,
        jobTemplate: {
            title: 'Monthly Fire Extinguisher Check',
            description: 'Inspect and certify all fire extinguishers in common areas.',
            priority: 'Medium',
            estimatedDurationMinutes: 90,
        },
        // This date is now set to 1 month ago, so the next due date is today.
        lastGeneratedUntil: subMonths(new Date(), 1).toISOString(), 
        createdAt: '2023-01-15T09:00:00.000Z',
    },
];

export const mockCustomers: CustomerData[] = [
    { id: 'cust_1', companyId: MOCK_COMPANY_ID, name: 'Eve Davis', phone: '555-0201', email: 'eve.d@example.com', address: '123 Maple St, Los Angeles, CA', createdAt: subDays(new Date(), 2).toISOString() },
    { id: 'cust_2', companyId: MOCK_COMPANY_ID, name: 'Frank Miller', phone: '555-0202', email: 'frank.m@example.com', address: '456 Oak Ave, Los Angeles, CA', createdAt: subDays(new Date(), 1).toISOString() },
    { id: 'cust_3', companyId: MOCK_COMPANY_ID, name: 'Grace Wilson', phone: '555-0203', email: 'grace.w@example.com', address: '789 Pine Ln, Los Angeles, CA', createdAt: today.toISOString() },
    { id: 'cust_4', companyId: MOCK_COMPANY_ID, name: 'Heidi Inc.', phone: '555-0204', email: 'contact@heidi.inc', address: '101 Business Blvd, Los Angeles, CA', createdAt: subDays(today, 10).toISOString() },
];

export const mockEquipment: Equipment[] = [
    { id: 'equip_1', companyId: MOCK_COMPANY_ID, customerId: 'cust_1', customerName: 'Eve Davis', name: 'Rheem Water Heater', model: 'XE50M06ST45U1', installDate: '2022-05-10', createdAt: '2022-05-10' },
];

export const mockProfileChangeRequests: ProfileChangeRequest[] = [
    {
        id: 'pcr_1',
        companyId: MOCK_COMPANY_ID,
        technicianId: 'tech_1',
        technicianName: 'Alice Johnson',
        requestedChanges: {
            phone: '555-0105',
            skills: ['HVAC', 'AC Repair', 'Furnace Maintenance', 'Refrigerant Handling', 'Boiler Repair'],
        },
        notes: 'Updated my phone number and added a new skill certification for boilers.',
        status: 'pending',
        createdAt: new Date().toISOString(),
    }
];

export const mockChatMessages: ChatMessage[] = [
    {
        id: 'msg_1',
        jobId: 'job_1',
        companyId: MOCK_COMPANY_ID,
        senderId: 'tech_1',
        senderName: 'Alice Johnson',
        receiverId: MOCK_ADMIN_ID,
        text: "I'm on my way to the 'No Hot Water' job. The previous one took a bit longer than expected.",
        timestamp: subMinutes(new Date(), 15).toISOString(),
        isRead: true,
    },
    {
        id: 'msg_2',
        jobId: 'job_1',
        companyId: MOCK_COMPANY_ID,
        senderId: MOCK_ADMIN_ID,
        senderName: 'Dispatcher',
        receiverId: 'tech_1',
        text: "Thanks for the update, Alice. Keep me posted if there are any issues finding the site.",
        timestamp: subMinutes(new Date(), 14).toISOString(),
        isRead: true,
    },
     {
        id: 'msg_3',
        jobId: 'job_3',
        companyId: MOCK_COMPANY_ID,
        senderId: MOCK_ADMIN_ID,
        senderName: 'Dispatcher',
        receiverId: 'tech_1',
        text: "After the 'Outlet Sparking' job, please check if you have a spare 20A breaker in your van. The next customer might need one.",
        timestamp: subMinutes(new Date(), 5).toISOString(),
        isRead: false,
    },
];

export const mockParts = [
    "Compressor",
    "Capacitor",
    "Contactor",
    "Refrigerant R-410A",
    "Thermostat",
    "Filter Drier",
    "Igniter",
    "P-Trap Assembly",
    "Faucet Cartridge",
    "Circuit Breaker (20A)",
    "GFCI Outlet"
];
